# Generated by Django 4.1.7 on 2023-03-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('estabelecimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('estabelecimento_nome', models.CharField(max_length=100)),
                ('estabelecimento_endereco', models.CharField(max_length=200)),
                ('estabelecimento_telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa_numero', models.IntegerField()),
                ('mesa_capacidade', models.IntegerField()),
                ('mesa_status', models.BooleanField(default=False)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
            ],
        ),
    ]
