# Generated by Django 4.1.7 on 2023-03-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_item', models.CharField(max_length=50)),
                ('car_descricao', models.CharField(max_length=100)),
                ('car_preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('gar_id', models.AutoField(primary_key=True, serialize=False)),
                ('gar_nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'garcom',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=100)),
                ('usu_cpf', models.CharField(max_length=14)),
                ('usu_telefone', models.CharField(max_length=15)),
                ('usu_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_numero', models.IntegerField()),
                ('mes_capacidade', models.IntegerField()),
                ('mes_status', models.CharField(max_length=10)),
                ('gar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.garcom')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_data', models.DateTimeField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.cardapio')),
                ('mes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.mesa')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.usuario')),
            ],
            options={
                'db_table': 'comanda',
            },
        ),
        migrations.AddField(
            model_name='cardapio',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.categoria'),
        ),
    ]
