# Generated by Django 4.1.7 on 2023-03-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estabelecimento',
            table='estabelecimento',
        ),
        migrations.AlterModelTable(
            name='mesa',
            table='mesa',
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
            ],
            options={
                'db_table': 'garcom',
            },
        ),
    ]
