# Generated by Django 4.1.7 on 2023-03-05 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_alter_estabelecimento_table_alter_mesa_table_garcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('comanda_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comanda',
            },
        ),
        migrations.RenameField(
            model_name='garcom',
            old_name='estabelecimento',
            new_name='estabelecimento_id',
        ),
        migrations.RenameField(
            model_name='garcom',
            old_name='id',
            new_name='garcom_id',
        ),
        migrations.RenameField(
            model_name='garcom',
            old_name='nome',
            new_name='garcom_nome',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='estabelecimento',
            new_name='estabelecimento_id',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserva_reserva', models.DateTimeField()),
                ('reserva_nome_cliente', models.CharField(max_length=100)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.mesa')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('recibo_id', models.AutoField(primary_key=True, serialize=False)),
                ('recibo_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo_taxas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.comanda')),
            ],
            options={
                'db_table': 'recibo',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_nome', models.CharField(max_length=100)),
                ('estabelecimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('item_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_menu_nome', models.CharField(max_length=100)),
                ('item_menu_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.menu')),
            ],
            options={
                'db_table': 'itemmenu',
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('item_comanda_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_comanda_quantidade', models.IntegerField()),
                ('comanda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.comanda')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.itemmenu')),
            ],
            options={
                'db_table': 'itemcomanda',
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='garcom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.garcom'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.mesa'),
        ),
    ]
