# Generated by Django 4.1.5 on 2023-03-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.menu')),
            ],
        ),
    ]
